### ISSUE TITLE
Automate configuration of mp-destination and token

### ISSUE THREAD

**Issue by cleverdevil** [cleverdevil/Indiepaper-macOS#1]
At present, Indiepaper for macOS requires that the user manually configure their target micropub endpoint and a bearer token. This is nice and explicit, but it isn't a particularly good user experience. It would be better if configuration was automated.

Currently, I am thinking that I should add auto-configuration via a URL handler for the macOS app. Something like this:

`indiepaper:configure?micropubTargetURL=https://aperture.p3k.io/micropub&amp;bearerToken=ASDF`

Then, when clicked, the link would launch Indiepaper for macOS, store the configuration, and let the user know that they're all set.

[](https://brid.gy/publish/github)

(Originally published at: https://cleverdevil.io/2018/automate-configuration-of-mp-destination-and-token)

**Comment by cleverdevil** [comment]
It would also be nice to add IndieAuth to the Indiepaper website, which could then generate bookmarklets and macOS configuration links automatically based upon the IndieAuth exchange.

For the use case of Aperture, the user would log into www.indiepaper.io with [https://aperture.p3k.io](https://aperture.p3k.io), and then would select a channel to publish to during the auth flow.

[](https://brid.gy/publish/github)

(Originally published at: https://cleverdevil.io/2018/it-would-also-be-nice-to-add-indieauth-to-the)

**Comment by manton** [comment]
Maybe this should be in a separate ticket, but just to capture what was said in the IndieWeb chat… We talked about using `scope=save` if Indiepaper supports IndieAuth for connecting to a Micropub endpoint automatically. Then the Micropub endpoint would know to route any POSTs to a special "read later" section.

**Comment by cleverdevil** [comment]
I've added support for auto-configuration of the macOS app via URL:

https://github.com/cleverdevil/Indiepaper-macOS/commit/fcbd376cd334998c79fa26be7795394131066ba8

In addition, I've made change to Indiepaper the service to support IndieAuth with `scope=save`:

https://github.com/cleverdevil/indiepaper/commit/cfe02fd13110122c15706953bd930dae6e2b9c58

... and a change to the Indiepaper website to support kicking off the IndieAuth exchange and then automatically generating the bookmarklet and macOS app configuration URL:

https://github.com/cleverdevil/indiepaper-website/commit/8a1ac14c3ab377c4ae7fcfb94b7998ed935a4ff1

Now, users can go to https://www.indiepaper.io/indieauth.html and login via IndieAuth, and automatically configure the macOS app, and drag a bookmarklet to their bookmarks bar.
